// templates/react-vite/src/App.tsx
export function App() {
  return (
    <main className="app-shell">
      <section className="panel">
        <p className="eyebrow">Generated React App</p>
        <h1>Ready for OpenCode</h1>
        <p>
          This starter app is intentionally small so the Agent can reshape it
          into the application requested by the user.
        </p>
      </section>
    </main>
  );
}

// templates/vue-vite/src/App.vue
<script setup lang="ts">
const message = "Ready for OpenCode";
</script>

<template>
  <main class="app-shell">
    <section class="panel">
      <p class="eyebrow">Generated Vue App</p>
      <h1>{{ message }}</h1>
      <p>
        This starter app is intentionally small so the Agent can reshape it
        into the application requested by the user.
      </p>
    </section>
  </main>
</template>
